### PR TITLE
make `mem_read` interface more versatile

### PR DESCRIPTION
**Pull request by strake**
#47 reminded me, i had been thinking about the `mem_read` interface...

The interface now invariably allocates, even if the caller has a buffer they could re-use. The new interface in this PR is more versatile and more closely follows `std::io`.

It's a little unfortunate we have no type to denote a potentially-uninitialized buffer; i have seen mention of a hypothetical `&out` type in other threads, a reference to potentially-uninitialized memory, which can be written but not read, but my just-woken-up self has been unable to find them this morning. If they adopt some such interface for `std::io` in future, we should also consider it here.

### CODE REVIEW

**Comment by ekse** [comment]
ping @strake in case you missed my response.

**Comment by strake** [comment]
Ah, life became busy and i forgot. I should respond properly sometime in the next few days.

**Comment by strake** [comment]
I defined a function `mem_read_as_vec` to do so. I think the function to read to a slice ought to have the shorter more ergonomic name, as it is a more basic use of the API, and likely more efficient. But if you feel strongly to the contrary, let me know.

**Comment by strake** [comment]
Thanks!

**Pull request merged**
