### PR TITLE
Windows build works out of the box

### PR DESCRIPTION
**Pull request by mthiesen**
Previously unicorn-rs and projects that depend on it could only be build using the "Visual Studio Developer Command Prompt".

I changed the unicorn-rs build script so that it locates the latest Visual Studio installation and invokes `msbuild` with the appropriate parameters.

I tested this with Visual Studio 2017 and Visual Studio 2015 for x86 and x64 builds.

### CODE REVIEW

**Comment by ekse** [comment]
Hi Malte, thank you very much for this pull request! I am currently away for the holidays, I will have access to my Windows computer when I come back home on the first week of January. If you don't mind I would like to test this change before merging it.

Happy holidays to you.

**Comment by mthiesen** [comment]
Sure, there is no need to rush this.

**Comment by ekse** [comment]
I found an issue, in msvc_build.bat `Platform=%4` should be `PlatformToolset=%4` instead.

`msbuild msvc/unicorn.sln /m /t:unicorn_static /p:OutDir="%~2/";%3useenv=true;Configuration=Release;PlatformToolset=%4`

**Comment by mthiesen** [comment]
No, Platform selects between Win32 and x64 builds, so actually it selects the architecture. Microsoft’s terminology is a little bit weird there.

The PlatformToolset is set with %3. It is possible that it is not set at all, in that case an empty string is used, otherwise it contains PlatformToolset=<TOOLSET_VERSION>;
Doing it this way ensures that the substitution yields a valid commandline in both cases.

**Comment by ekse** [comment]
Ok sorry about the confusion, on my system the PlatformToolset value is being split at the equal sign and I'm ending up with the toolset version at position %4. 

`msbuild msvc/unicorn.sln /m /t:unicorn_static /p:OutDir="D:\projects\Rust\unicorn-rs\target\debug\build\libunicorn-sys-c091f39077832019\out/";PlatformToolsetuseenv=true;Configuration=Release;Platform=v141_xp` 
 
It seems that batch files split arguments at `=` characters.
https://stackoverflow.com/questions/20572424/preserving-equal-characters-in-batch-file-parameters

**Comment by mthiesen** [comment]
I see, I will look into this later today.

**Comment by mthiesen** [comment]
OK, I fixed the problem. This was actually harder than I thought, first I just wanted to wrap the parameter in double quotes to keep it from being split at the `=`. However `std::process::Command` automatically quotes all argument strings that contain whitespace, all quotes already present are automatically escaped.

I had to work around this with additional batch logic.

**Comment by ekse** [comment]
Nice, it is working fine now. merging.

**Pull request merged**
